### ISSUE TITLE
etherpad: directly run node server.js in systemd unit

### ISSUE THREAD

**Issue by muxator** [m3047/pangolin#1]
Currentl, the systemd unit that launches Etherpad runs a shell script: 
https://github.com/m3047/pangolin/blob/d2dd93c41efc0f5fd667c4278a34ecd84d22729b/ansible/roles/etherpad_server/files/etherpad.service#L8

That ultimately runs Etherpad's `bin/run.sh`.

Actually, once all its dependencies are installed, Etherpad can be run in a simpler way (have a look at last line of [bin/run.sh](https://github.com/ether/etherpad-lite/blob/3b24c97d1eb49a3bbd429d3491e8bc61c85be0ce/bin/run.sh#L38
)):

```bash
node "/PATH/TO/ETHERPAD/node_modules/ep_etherpad-lite/node/server.js" "$@"
```

A good example is the first systemd unit listed in https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service.

On the other side, the dependencies could be installed by the ansible script running 'bin/installDeps.sh` once.

**Comment by m3047** [comment]
@muxator thanks for the pointer to `installDeps.sh`. I made that change. I also changed the systemd unit file to call `node` directly and it seems to work; I'm not sure it's an improvement over calling a script from a UX perspective (my personal preference is to do things the same way everywhere, and so have systemd do it the way a user would absent a compelling argument) but you provided a link to instructions on how to do so so why not.

I think there are some conflicting objectives, so I should probably memorialize mine: _1) Everything specific to running Etherpad is installed under a dedicated user, and it is possible and correct to run etherpad as that user from a login shell. 2) Ansible as well as Systemd have some idiosyncracies around running something as a different user._

Both _Node_ and _Etherpad_ are deployed ("installed" isn't really the right word) under the `etherpad` user's home directory `/home/etherpad/` and the `PATH` is updated in the `etherpad` user's `.profile` (along with `NODE_ENV=production`).

The key feature of `run-etherpad.sh` was the shebang line which makes it a login shell:

```
#!/bin/bash -l
```

`sudo` has the `-i` option to invoke a login shell, and it doesn't seem like the `PATH` is needed when `node` is invoked directly from the systemd unit file.
